### ISSUE TITLE
[Bug] TTY width broken when resizing Terminator with Fish. No arrow keys support. Some colors are broken

### ISSUE THREAD

**Issue by atraest** [n4n0GH/task#4]
**Steps to reproduce (broken TTY width)**

1. Open Terminator terminal.
2. Enter Fish shell.
3. Add a task.
4. Resize the terminal.

**Steps to reproduce (lack of arrow support)**

1. Type a task.
2. Try using left and right arrows to navigate through the line that you've typed.

**Steps to reproduce (broken colors)**

1. Install and switch to some famous color scheme, like Ayu for example. Have transparency enabled.

**Current behaviour**

- Can't resize the terminal without braking the visibility of the application. Unable to see the action warning messages, they stop halfway.
- Can't navigate through what you've typed.
- Unable to see the "NORMAL" section message in some terminal themes/color schemes. Demonstrated on the screenshot below.

**Expected behaviour**

- Able to resize the terminal without breaking TTY width or impeding action warning messages from showing.
- Able to navigate with arrow keys so you can fix typos, instead of using backspace repeatedly.
- We should be able to see the "NORMAL" section message regardless of terminal theme/color scheme.

![task-bug](https://user-images.githubusercontent.com/57003922/73097734-999ef680-3ec6-11ea-9185-86cdab4d6146.png)

**Comment by n4n0GH** [comment]
Fixed arrow key stuff and resizing of modeline; however the colors of various colorscheme can stay broken for all I care. They are using non-standard colors with sometimes way too little contrast and fixing the colors for one scheme will break them for others. Sorry if it looks like crap on your favorite color scheme uwu
